### ISSUE TITLE
Using static_node_count

### ISSUE THREAD

**Issue by AGiantSquid** [FluidNumerics/slurm-gcp#3]
I think there is a bug when using static_node_count in the configuration.

I've got a setup like this:

```
    partitions :

           - name                  : shared_cpu
             machine_type          : n1-standard-2
             static_node_count     : 2
             max_node_count        : 10
             zone                  : us-central1-b
             preemptible_bursting  : True

           - name                  : shared_gpu
             machine_type          : n1-standard-16
             max_node_count        : 4
             static_node_count     : 4
             zone                  : us-central1-b
             preemptible_bursting  : True
```

I expect that I will have 2 cpu nodes up all the time, with the ability to expand to up to 10 if the workload requires it, and to always have exactly 4 gpu nodes up all the time. When I start the cluster, I see the following:

![before](https://user-images.githubusercontent.com/26531374/61737927-d0952380-ad4e-11e9-8ee3-ffd64d7a8602.PNG)

It looks like the compute nodes that start 0000x are the "shared_cpu" nodes, and the nodes that start 0100x are the "shared_gpu" nodes. When I run a command, however, like 

```sbatch --array=1-4 ./test.sh```

I see this happen:

![after](https://user-images.githubusercontent.com/26531374/61737963-e6a2e400-ad4e-11e9-825e-d4469c942f61.PNG)

It seems to re-spawn the cpu nodes that were sitting around waiting for a job:

![image](https://user-images.githubusercontent.com/26531374/61737999-f7ebf080-ad4e-11e9-9c24-bad443e31367.png)

Is this a bug, or does static_node_count not work with partitions? I was hoping to have some nodes always up to same time on them spawning.

**Comment by yuanzhou** [comment]
I was wondering where to set the `static_node_count` and looked at the `slurm-cluster.yaml` in the master branch. I didn't see that option. I tested the partition and by default each partition has one static node. Wish I could set it as 0 to start with.

**Comment by schoonovernumerics** [comment]
@AGiantSquid 
The bottom two images you've shared indicating a typo in our naming convention for static and cloud nodes. It looks like we included a `-` between `compute` and the node id for the static nodes, but not for the cloud nodes. The slurm.conf file references the cloud node naming convention ( without the `-` )

I just pushed up a commit ( 5d285fe ) that corrects the static node id. Could you re-deploy with the latest commit to master and try again ?

**Comment by schoonovernumerics** [comment]
@yuanzhou by default, the static node count for each partition is zero.
The [slurm.jinja.schema](https://github.com/FluidNumerics/slurm-gcp/blob/master/slurm.jinja.schema#L330) specifies that the `static_node_count` is part of the partition array object.

When the cluster launches, image nodes are created and a snapshot of the disk is made so that future compute nodes can reference that image as a boot image. After creating the snapshot, the image nodes are stopped so that you don't incur additional charges for these resources ( other than the disks and images)

**Comment by AGiantSquid** [comment]
@schoonovernumerics The latest changes have indeed fixed my issue. Thanks! 💯

**Comment by schoonovernumerics** [comment]
Glad to hear it! Closing this issue
