### ISSUE TITLE
Cluster with spawned nodes still up won't delete properly.

### ISSUE THREAD

**Issue by AGiantSquid** [FluidNumerics/slurm-gcp#4]
Steps to reproduce:
1. Start cluster with `max-node_count` higher than `static_node_count` for a partition.
    ```yaml
    # slurm-cluster.yaml
    ...
    partitions :
        - name               : partition_one
          max_node_count     : 10
          static_node_count  : 2
    ...
    ```
    `$ gcloud deployment-manager deployments create slurm-cluster --config slurm-cluster.yaml`
1. Run job with more nodes that are in `static_node_count`.
    `$ sbatch --array=1-4 ./test.sh`
1. Extra nodes should automatically spawn.
1. After the job finishes, try to delete the cluster (while the compute nodes that ran the job are still up.)
    `gcloud deployment-manager deployments delete slurm-cluster`
1. Get error: 
    ```Waiting for delete [operation-1563915743098-58e5f825376c4-38d102d9-f5c26e6f]...failed .
    ERROR: (gcloud.deployment-manager.deployments.delete) Delete operation operation-1563915743098-58e5f825376c4-38d102d9-f5c26e6f failed.
    Error in Operation [operation-1563915743098-58e5f825376c4-38d102d9-f5c26e6f]: errors: - code: RESOURCE_ERROR
      location: /deployments/slurm-cluster/resources/slurm-cluster-slurm-subnet
      message: "{\"ResourceType\":\"compute.v1.subnetwork\",\"ResourceErrorCode\":\"400\"\
        ,\"ResourceErrorMessage\":{\"code\":400,\"errors\":[{\"domain\":\"global\",\"\
        message\":\"The subnetwork resource 'projects/gk-transcription/regions/us-central1/subnetworks/slurm-cluster-slurm-subnet'\
        \ is already being used by 'projects/gk-transcription/zones/us-central1-b/instances/slurm-cluster-compute000003'\"\
        ,\"reason\":\"resourceInUseByAnotherResource\"}],\"message\":\"The subnetwork\
        \ resource 'projects/gk-transcription/regions/us-central1/subnetworks/slurm-cluster-slurm-subnet'\
        \ is already being used by 'projects/gk-transcription/zones/us-central1-b/instances/slurm-cluster-compute000003'\"\
        ,\"statusMessage\":\"Bad Request\",\"requestPath\":\"https://www.googleapis.com/compute/v1/projects/gk-transcription/regions/us-central1/subnetworks/slurm-cluster-slurm-subnet\"\
        ,\"httpMethod\":\"DELETE\"}}"
    ```
The newly created nodes are not included in the cluster, evidently, and are not told to go down.

If I manually delete the spawned nodes, the cluster will delete fine.

**Comment by schoonovernumerics** [comment]
Can you include your test.sh in this issue ?

**Comment by schoonovernumerics** [comment]
If you try to delete the cluster while the burst nodes are still online, deplyoment deletion will fail given that the burst nodes are not part of the deployment manager manifest.

The problem for deletion is that the vpc network cannot be taken down when it is in use by other resources not in the deployment manifest.

To delete the cluster, you need to wait until the burst nodes are deleted or delete them manually. On the cluster you can send the node list to /apps/slurm/scripts/suspend.py. alternatively, you can use the gcloud ask or the compute engine hi.

**Comment by schoonovernumerics** [comment]
Closing this issue, as this behavior is an expected interaction between the slurm-gcp deployment and deployment-manager
