### ISSUE TITLE
"startup-script-compute" in "slurm.jinja" possibly unneeded?

### ISSUE THREAD

**Issue by AGiantSquid** [FluidNumerics/slurm-gcp#7]
I see an entry in the `slurm.jinja` for a `startup-script-compute` that I don't think is used anywhere. 

https://github.com/FluidNumerics/slurm-gcp/blob/5d285fec174efdd9b44567037bce8fe2435cedeb/slurm.jinja#L131

Am I correct in assuming it is unneeded? It looks like the compute nodes will import their respective startup-scripts elsewhere in the file.

It looks like the controller node saves this file to the `/apps/slurm/scripts` directory here:
https://github.com/FluidNumerics/slurm-gcp/blob/5d285fec174efdd9b44567037bce8fe2435cedeb/scripts/startup-script.py#L706

but I don't understand where it is being used.

**Comment by schoonovernumerics** [comment]
That startup-script is copied into `/apps/slurm/scripts` to be used in the possible event that a compute node image is not created or available for use. `/apps/slurm/scripts/startup-script.py` is referenced in [resume.py](https://github.com/FluidNumerics/slurm-gcp/blob/master/scripts/resume.py#L114)

**Comment by AGiantSquid** [comment]
Ah, that makes sense. Thanks!
